[versions]
kotlin = "2.2.0"
quarkus = "3.25.0"
truthish = "1.0.3"

[libraries]
quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin" }
quarkus-rest-kotlin-serialization = { module = "io.quarkus:quarkus-rest-kotlin-serialization" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-rest = { module = "io.quarkus:quarkus-rest" }
quarkus-config-yaml = { module = "io.quarkus:quarkus-config-yaml" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5" }

rest-assured = { module = "io.rest-assured:rest-assured" }

truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
