[versions]
awaitility = "4.3.0"
mongo = "5.6.3"
opensearch = "3.2.2"
quarkus = "3.31.3"
truth = "1.4.5"

[libraries]
awaitility = { module = "org.awaitility:awaitility", version.ref = "awaitility" }

mongo-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongo" }
mongo-driver = { module = "org.mongodb:mongodb-driver-sync" }

quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-rest-jackson = { module = "io.quarkus:quarkus-rest-jackson" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-rest = { module = "io.quarkus:quarkus-rest" }
quarkus-config-yaml = { module = "io.quarkus:quarkus-config-yaml" }
quarkus-mongodb-client = { module = "io.quarkus:quarkus-mongodb-client" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5" }
quarkus-redis = { module = "io.quarkus:quarkus-redis-client" }
quarkus-virtual-threads = { module = "io.quarkus:quarkus-virtual-threads" }
quarkus-opensearch-java-client = { module = "io.quarkiverse.opensearch:quarkus-opensearch-java-client", version.ref = "opensearch" }
quarkus-opensearch-transport-apache = { module = "io.quarkiverse.opensearch:quarkus-opensearch-transport-apache", version.ref = "opensearch" }

rest-assured = { module = "io.rest-assured:rest-assured" }

truth = { module = "com.google.truth:truth", version.ref = "truth" }

[plugins]
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
