[versions]
coroutines = "1.10.2"
kotlin = "2.3.0"
mongo = "5.6.1"
quarkus = "3.30.5"
truthish = "1.0.4"

[libraries]
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

mongo-bom = { module = "org.mongodb:mongodb-driver-bom", version.ref = "mongo" }
mongo-driver = { module = "org.mongodb:mongodb-driver-kotlin-coroutine" }

quarkus-bom = { module = "io.quarkus.platform:quarkus-bom", version.ref = "quarkus" }
quarkus-kotlin = { module = "io.quarkus:quarkus-kotlin" }
quarkus-rest-kotlin-serialization = { module = "io.quarkus:quarkus-rest-kotlin-serialization" }
quarkus-arc = { module = "io.quarkus:quarkus-arc" }
quarkus-rest = { module = "io.quarkus:quarkus-rest" }
quarkus-config-yaml = { module = "io.quarkus:quarkus-config-yaml" }
quarkus-mongodb-client = { module = "io.quarkus:quarkus-mongodb-client" }
quarkus-junit5 = { module = "io.quarkus:quarkus-junit5" }

rest-assured = { module = "io.rest-assured:rest-assured" }

truthish = { module = "com.varabyte.truthish:truthish", version.ref = "truthish" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-allopen = { id = "org.jetbrains.kotlin.plugin.allopen", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
quarkus = { id = "io.quarkus", version.ref = "quarkus" }
