apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: playground-

namespace: playground-namespace

labels:
  - pairs:
      app: playground-app
    includeSelectors: true

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml
