apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quarkus-playground.fullname" . }}-deployment
  namespace: {{ include "quarkus-playground.namespace" . }}
  labels:
    {{- include "quarkus-playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "quarkus-playground.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quarkus-playground.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          env:
            - name: QUARKUS_MONGODB_HOSTS
              value: "{{ .Values.mongodb.clusterServiceName }}.{{ include "quarkus-playground.namespace" . }}.svc.cluster.local:27017"
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.clusterName }}-psmdb-d-secrets
                  key: MONGODB_DATABASE_ADMIN_USER
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongodb.clusterName }}-psmdb-d-secrets
                  key: MONGODB_DATABASE_ADMIN_PASSWORD
            - name: QUARKUS_MONGODB_CREDENTIALS_AUTH_SOURCE
              value: "{{ .Values.mongodb.authDatabase }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
