apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "quarkus-playground.fullname" . }}-deployment
  namespace: {{ include "quarkus-playground.namespace" . }}
  labels:
    {{- include "quarkus-playground.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.quarkus.replicaCount }}
  selector:
    matchLabels:
      {{- include "quarkus-playground.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "quarkus-playground.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: app
          image: "{{ .Values.quarkus.image.repository }}:{{ .Values.quarkus.image.tag }}"
          imagePullPolicy: {{ .Values.quarkus.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.quarkus.service.targetPort }}
          env:
            - name: QUARKUS_MONGODB_HOSTS
              value: "{{- include "quarkus-playground.mongoHosts" .}}"
            - name: QUARKUS_MONGODB_CREDENTIALS_USERNAME
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secrets
                  key: MONGODB_DATABASE_ADMIN_USER
            - name: QUARKUS_MONGODB_CREDENTIALS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mongo-secrets
                  key: MONGODB_DATABASE_ADMIN_PASSWORD
            - name: QUARKUS_MONGODB_CREDENTIALS_AUTH_SOURCE
              value: "{{ .Values.mongo.authDatabase }}"
            - name: QUARKUS_REDIS_HOSTS
              value: "{{- include "quarkus-playground.redisHosts" .}}"
            - name: QUARKUS_REDIS_CLIENT_TYPE
              value: "cluster"
            - name: QUARKUS_OPENSEARCH_HOSTS
              value: "{{- include "quarkus-playground.opensearchHosts" .}}"
          resources:
            {{- toYaml .Values.quarkus.resources | nindent 12 }}
