{{- if .Values.namespace.create }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "quarkus-playground.namespace" . }}
  labels:
    {{- include "quarkus-playground.labels" . | nindent 4 }}
{{- end }}
