apiVersion: v1
kind: Service
metadata:
  name: {{ include "quarkus-playground.fullname" . }}-service
  namespace: {{ include "quarkus-playground.namespace" . }}
  labels:
    {{- include "quarkus-playground.labels" . | nindent 4 }}
spec:
  type: {{ .Values.quarkus.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.quarkus.service.port }}
      targetPort: {{ .Values.quarkus.service.targetPort }}
  selector:
    {{- include "quarkus-playground.selectorLabels" . | nindent 4 }}
